-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 08:44:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema makeabet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema makeabet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makeabet` DEFAULT CHARACTER SET utf8 ;
USE `makeabet` ;

-- -----------------------------------------------------
-- Table `makeabet`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeabet`.`player` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `balance` DOUBLE NOT NULL DEFAULT 1000,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makeabet`.`balance_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeabet`.`balance_transaction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `player_id` BIGINT NOT NULL,
  `amount` DOUBLE NULL,
  `amount_before` DOUBLE NULL,
  PRIMARY KEY (`id`, `player_id`),
  INDEX `fk_balance_transaction_player_idx` (`player_id` ASC),
  CONSTRAINT `fk_balance_transaction_player`
    FOREIGN KEY (`player_id`)
    REFERENCES `makeabet`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makeabet`.`bet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeabet`.`bet` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `player_id` BIGINT NOT NULL,
  `stake_amount` DOUBLE NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bet_player1_idx` (`player_id` ASC),
  CONSTRAINT `fk_bet_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `makeabet`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makeabet`.`bet_selections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeabet`.`bet_selections` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `bet_id` BIGINT NOT NULL,
  `selection_id` BIGINT NOT NULL,
  `odds` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bet_selections_bet1_idx` (`bet_id` ASC),
  CONSTRAINT `fk_bet_selections_bet1`
    FOREIGN KEY (`bet_id`)
    REFERENCES `makeabet`.`bet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
